config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
# frozen_string_literal: true

# Kittens resource controller
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to @kitten, flash: { success: 'Kitten succesfully created.' }
    else
      flash.now[:alert] = 'This kitten could not be created.'
      render :new
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to @kitten, flash: { success: 'Kitten succesfully updated.' }
    else
      flash.now[:alert] = 'This kitten could not be updated.'
      render :edit
    end
  end

  def destroy
    kitten = Kitten.find(params[:id])
    if kitten.destroy
      redirect_to root_path, flash: { success: 'Kitten succesfully deleted.' }
    else
      redirect_back fallback_location: root_path,
                    flash: { alert: 'This kitten could not be deleted.' }
    end
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<% if kitten.errors.any? %>
  <h3>Errors</h3>
  <div class="errors">
    <ul>
      <% kitten.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul> 
  </div>
<% end %>

<%= form_with model: kitten do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :cuteness %>
    <%= f.select :cuteness, %w[very incredibly astronomically] %>
  </div>                       

  <div class="field">
    <%= f.label :softness%>
    <%= f.select :softness, %w[silky fluffy puffy] %>
  </div>

  <div class="field">
    <%= f.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h2>Edit kitten</h2>
<%= render partial: "kittens/form", locals: { kitten: @kitten } %>
<%= link_to 'Delete', kitten_path(@kitten), method: :delete %>

app/views/kittens/index.html.erb
<h2>Kittens</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Cuteness</th>
    <th>Softness</th>
  </tr>

  <% @kittens.each do |kitten| %>
    <tr>
      <td><%= kitten.name %></td>
      <td><%= kitten.age %></td>
      <td><%= kitten.cuteness %></td>
      <td><%= kitten.softness %></td>
      <td>
        <%= link_to 'Delete', kitten_path(kitten), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/kittens/new.html.erb
<h2>Create a kitten</h2>
<%= render partial: "kittens/form", locals: { kitten: @kitten } %>

app/views/kittens/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Cuteness</th>
    <th>Softness</th>
  </tr>

  <tr>
    <td><%= @kitten.name %></td>
    <td><%= @kitten.age %></td>
    <td><%= @kitten.cuteness %></td>
    <td><%= @kitten.softness %></td>
    <td>
      <%= link_to 'Delete', kitten_path(@kitten), method: :delete %>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash.any? %>
      <% flash.each do |type, message| %>
        <div class="notification type">
            <p><%= message %></p> 
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>